# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('categories', models.ManyToManyField(to='images.categories')),
            ],
        ),
        migrations.RenameModel(
            old_name='Editor',
            new_name='Photographer',
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Photographer'),
        ),
    ]
